<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="soccf-tr5-001" name="component-tests(failed)(failed)" tests="1" failures="1" timestamp="8 Oct 2014 11:55:52 GMT" time="1.591" errors="0">
  <testcase name="testUpdateStudentProfilePicture" time="0.873" classname="teammates.test.cases.storage.ProfilesDbTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at teammates.test.cases.storage.ProfilesDbTest.testUpdateProfilePictureSuccessWithNewPictureKey(ProfilesDbTest.java:255)
	at teammates.test.cases.storage.ProfilesDbTest.testUpdateStudentProfilePicture(ProfilesDbTest.java:172)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateStudentProfilePicture -->
</testsuite> <!-- component-tests(failed)(failed) -->
