<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="soccf-tr5-001" name="occasional-tests" tests="13" failures="1" timestamp="8 Oct 2014 12:10:05 GMT" time="176.96" errors="0">
  <testcase name="testStableSort" time="0.437" classname="teammates.test.cases.ui.browsertests.TableSortTest"/>
  <testcase name="testTableSortingDate" time="0.219" classname="teammates.test.cases.ui.browsertests.TableSortTest"/>
  <testcase name="testTableSortingDiff" time="0.202" classname="teammates.test.cases.ui.browsertests.TableSortTest"/>
  <testcase name="testTableSortingID" time="0.282" classname="teammates.test.cases.ui.browsertests.TableSortTest"/>
  <testcase name="testTableSortingName" time="0.203" classname="teammates.test.cases.ui.browsertests.TableSortTest"/>
  <testcase name="testTableSortingPoint" time="0.218" classname="teammates.test.cases.ui.browsertests.TableSortTest"/>
  <testcase name="loadWebpageCompilation" time="34.309" classname="teammates.test.cases.ui.browsertests.MashupPageUiTest"/>
  <testcase name="executeJsTests" time="7.824" classname="teammates.test.cases.ui.browsertests.AllJsTests">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at teammates.test.cases.ui.browsertests.AllJsTests.executeJsTests(AllJsTests.java:47)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- executeJsTests -->
  <testcase name="testAssertionError" time="1.731" classname="teammates.test.cases.ui.browsertests.SystemErrorEmailReportTest"/>
  <testcase name="testDeadlineExceededException" time="1.092" classname="teammates.test.cases.ui.browsertests.SystemErrorEmailReportTest"/>
  <testcase name="testEntityDoesNotExistException" time="1.544" classname="teammates.test.cases.ui.browsertests.SystemErrorEmailReportTest"/>
  <testcase name="testNullPointerException" time="1.482" classname="teammates.test.cases.ui.browsertests.SystemErrorEmailReportTest"/>
  <testcase name="testUnauthorizedAccessException" time="2.06" classname="teammates.test.cases.ui.browsertests.SystemErrorEmailReportTest"/>
</testsuite> <!-- occasional-tests -->
